### ISSUE TITLE
Errors when building with Visual Studio IDE

### ISSUE THREAD

**Issue by AnubisYinepu** [Organic-Code/Breep#13]
I get the following errors during compilation ( Microsoft Visual Studio Ultimate 2013):
error C2144: syntax error : 'bool' should be preceded by ';'
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
etc.
all in type_traits.hpp.
Unfortunately I do not have any experience using GCC.
It will be much appreciated if you could help.

**Comment by Organic-Code** [comment]
I fail to see what could cause such error, and I suspect that it is due to MSVS 2013 not fully supporting c++14, which is required by this library.

Nonetheless I will try to modify the source code to make it compliant with MSVS 2013 like I did with GCC5 if possible 

Do you have further informations about this error? Line numbers after macro expension would be helpfull

**Comment by AnubisYinepu** [comment]
Thanks for your amazingly fast response.

Started a new project in VC, Win32 Console Application, .NET Framework 4.5.
Used file chat/main.cpp (pasted in .cpp)
compiled Release x64

Error	1	error C2144: syntax error : 'bool' should be preceded by ';'	<User dir>\Breep-master\include\breep\util\type_traits.hpp	153	1	Chat
Error	2	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	<User dir>\Breep-master\include\breep\util\type_traits.hpp	153	1	Chat
Error	3	error C2039: 'index_sequence' : is not a member of 'std'	<User dir>\Breep-master\include\breep\util\type_traits.hpp	197	1	Chat
Error	4	error C2988: unrecognizable template declaration/definition	<User dir>\Breep-master\include\breep\util\type_traits.hpp	197	1	Chat
Error	5	error C2059: syntax error : '->'	<User dir>\Breep-master\include\breep\util\type_traits.hpp	197	1	Chat
Error	6	error C2065: 'remove_type' : undeclared identifier	<User dir>\Breep-master\include\breep\util\type_traits.hpp	230	1	Chat
Error	7	error C3544: 'T': parameter pack expects a type template argument	<User dir>\Breep-master\include\breep\util\type_traits.hpp	230	1	Chat
Error	8	error C2766: explicit specialization; 'breep::detail::networking_traits_impl<char16_t>' has already been defined	<User dir>\Breep-master\include\breep\util\type_traits.hpp	248	1	Chat
Error	9	error C2766: explicit specialization; 'breep::detail::networking_traits_impl<char32_t>' has already been defined	<User dir>\Breep-master\include\breep\util\type_traits.hpp	250	1	Chat
Error	10	error C2610: 'breep::basic_peer<io_manager>::basic_peer(breep::basic_peer<io_manager> &&)' : is not a special member function which can be defaulted	<User dir>\Breep-master\include\breep\network\basic_peer.hpp	74	1	Chat
Error	11	error C2610: 'breep::basic_peer<io_manager> &breep::basic_peer<io_manager>::operator =(breep::basic_peer<io_manager> &&)' : is not a special member function which can be defaulted	<User dir>\Breep-master\include\breep\network\basic_peer.hpp	84	1	Chat
Error	12	error C3646: 'noexcept' : unknown override specifier	<User dir>\Breep-master\include\breep\network\basic_peer.hpp	90	1	Chat
Error	13	error C3646: 'noexcept' : unknown override specifier	<User dir>\Breep-master\include\breep\network\basic_peer.hpp	96	1	Chat
Error	14	error C3646: 'noexcept' : unknown override specifier	<User dir>\breep-master\include\breep\network\impl\basic_peer.tcc	22	1	Chat
Error	15	error C3646: 'noexcept' : unknown override specifier	<User dir>\breep-master\include\breep\network\impl\basic_peer.tcc	27	1	Chat
Error	16	error C2039: 'index_sequence' : is not a member of 'std'	<User dir>\Breep-master\include\breep\util\tuple_iter.hpp	38	1	Chat
Error	17	error C2061: syntax error : identifier 'index_sequence'	<User dir>\Breep-master\include\breep\util\tuple_iter.hpp	38	1	Chat
Error	18	error C3547: template parameter 'I' cannot be used because it follows a template parameter pack and cannot be deduced from the function parameters of 'breep::detail::for_each_helper'	<User dir>\Breep-master\include\breep\util\tuple_iter.hpp	38	1	Chat
Error	19	error C2039: 'index_sequence' : is not a member of 'std'	<User dir>\Breep-master\include\breep\util\tuple_iter.hpp	43	1	Chat
Error	20	error C2061: syntax error : identifier 'index_sequence'	<User dir>\Breep-master\include\breep\util\tuple_iter.hpp	43	1	Chat
Error	21	error C3547: template parameter 'I' cannot be used because it follows a template parameter pack and cannot be deduced from the function parameters of 'breep::detail::for_each_helper'	<User dir>\Breep-master\include\breep\util\tuple_iter.hpp	43	1	Chat
Error	22	error C2597: illegal reference to non-static member 'breep::type_traits<uint_fast8_t &>::is_any_ptr'	<User dir>\breep-master\include\breep\util\impl\deserializer.tcc	102	1	Chat
Error	23	error C2597: illegal reference to non-static member 'breep::type_traits<uint_fast8_t &>::is_any_ptr'	<User dir>\breep-master\include\breep\util\impl\deserializer.tcc	104	1	Chat
Error	24	error C2597: illegal reference to non-static member 'breep::type_traits<uint_fast8_t &>::is_any_ptr'	<User dir>\breep-master\include\breep\util\impl\deserializer.tcc	329	1	Chat
Error	25	error C2597: illegal reference to non-static member 'breep::type_traits<uint_fast8_t &>::is_any_ptr'	<User dir>\breep-master\include\breep\util\impl\deserializer.tcc	535	1	Chat
Error	26	error C3551: expected a trailing return type	<User dir>\Breep-master\include\breep\network\detail\utils.hpp	38	1	Chat
Error	27	error C2144: syntax error : 'bool' should be preceded by ';'	<User dir>\Breep-master\include\breep\network\detail\utils.hpp	109	1	Chat
Error	28	error C4430: missing type specifier - int assumed. Note: C++ does not support default-int	<User dir>\Breep-master\include\breep\network\detail\utils.hpp	109	1	Chat
Error	29	error C2146: syntax error : missing ';' before identifier 'is_const_ref'	<User dir>\Breep-master\include\breep\network\detail\utils.hpp	152	1	Chat
Error	30	error C1903: unable to recover from previous error(s); stopping compilation	<User dir>\Breep-master\include\breep\network\detail\utils.hpp	152	1	Chat
	31	IntelliSense: 'constexpr' is not valid here	<User dir>\Breep-master\include\breep\network\detail\utils.hpp	152	7	Chat

**Comment by Organic-Code** [comment]
There's too much things unsupported by MSVC 2013 here.

Althought it might be fixable if you are willing to drop constexpr, noexept and probably other things, it would take too much time for me to fix it

All I can say is that you should update to a more recent version of MSVC, sorry

**Comment by AnubisYinepu** [comment]
Understood, thanks for the help.

**Comment by Organic-Code** [comment]
Thanks for reporting the issue anyway :)
