### ISSUE TITLE
Possibility for network discovery/broadcast messages?

### ISSUE THREAD

**Issue by han-so1omon** [Organic-Code/Breep#9]
I'm interested in using this library for a project involving ad-hoc network building. How would you suggest building network discovery features to Breep? The simplest way that I can think of is to add broadcast messaging (using UDP, I suppose) to build a routing table. At least one problem with that, though, is that UDP still needs a router I think. Is there some forum where we could discuss this?

Alternatively, do you have links to sources where I can learn true peer-to-peer communication paradigm? Perhaps you have a diagram of Breep's comm flow or know of a similar one.

Cheers

**Comment by Organic-Code** [comment]
Well, for network discovery it is indeed easier if you have some way to broadcast messages, but as far as I'm aware it's always through a router. But then again, I'm not sure I understood completely what you're aiming at. If all the computers of your network are connected to a router, then it's no problem and you should be able to broadcast. If on the other hand the network itself is all in a peer to peer fashion, then you'll have to find something else I guess. I'll try to think about it

I'm not currently active in any forum, but if you open a thread on some, I'd be glad to help there (only if it's an English or French speaking forum though :p)

I have no diagram of Breep's working flow atm (which could potentially be an issue anyway if I go back to that project someday, which I think I will). I might write one for the global idea behind it if you want. It's pretty straight forward actually.

**Comment by han-so1omon** [comment]
The idea is to have a lightweight, ad-hoc networking library for drones (i.e. very mobile robots, mostly aerial), which corresponds with some of my research. Useful in the event that there is no central routing authority and that network links can break/form arbitrarily. I'll do some more research and let you know if I propagate this to another forum. Would definitely be interested in collaborating. If you have the time then a simple flow chart would help me understand the peer-to-peer process in Breep, and it would be fodder for related ideas.
